QuickSearchESConfig:
  Host: https://10.20.70.29:9200
  User: elastic
  Password: ma96ehw5b
  # Host: https://127.0.0.1:9200
  # User: elastic
  # Password: ma96ehw5b
  ResponseHeaderTimeoutSeconds: 100
  # Host: https://10.20.70.22:9200
  # User: elastic
  # Password: pacman

PEVCMySQLConfig:
  # Host: 127.0.0.1
  # Port: 3306
  # User: root
  # Password: root
  # DBName: dataapp_pevc
  # LogMode: true
  Host: 10.20.70.24
  Port: 3306
  User: prod_da_pevc_user
  Password: A3qHdfHw6SP4mGTKOezKZxj8
  DBName: prod_da_pevc
  LogMode: console